# Generated by Django 4.2 on 2024-09-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_image', models.ImageField(default='restaurant_default.jpg', upload_to='restaurant_images')),
                ('restaurant_location', models.CharField(max_length=100)),
                ('restaurant_slug', models.SlugField(blank=True, unique=True)),
                ('restaurant_phone', models.IntegerField(unique=True)),
                ('restaurant_about', models.TextField()),
                ('restaurant_featured', models.BooleanField(blank=True)),
            ],
        ),
    ]
