# Generated by Django 4.2 on 2024-09-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_image', models.CharField(default='https://900degreespizza.com/wp-content/uploads/2019/10/chairs-cutlery-fork-9315.jpg', max_length=1000)),
                ('restaurant_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.CharField(default='https://st3.depositphotos.com/4060975/18243/v/450/depositphotos_182439216-stock-illustration-flat-icon-food-menu.jpg', max_length=1000)),
                ('restauraunt_belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_by_restaurant', to='food.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://worldfoodtour.co.uk/wp-content/uploads/2013/06/neptune-placeholder-48.jpg', max_length=1000)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods_by_category', to='food.itemcategory')),
            ],
        ),
    ]
