# Generated by Django 4.2 on 2024-09-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_slug', models.SlugField(blank=True)),
                ('menu_image', models.ImageField(default='menu_category_default.jpg', upload_to='restaurant_images')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_image', models.ImageField(default='restaurant_default.jpg', upload_to='restaurant_images')),
                ('restaurant_location', models.CharField(max_length=100)),
                ('restaurant_slug', models.SlugField(blank=True, unique=True)),
                ('restaurant_phone', models.IntegerField(unique=True)),
                ('restaurant_about', models.TextField()),
                ('restaurant_featured', models.BooleanField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_by_city', to='food.city')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('social_image', models.ImageField(default='social_icon.jpg', upload_to='social_icon_images')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_icons', to='food.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant_image', models.ImageField(default='restaurant_details-img.jpg', upload_to='restaurant_details_images')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_imgs', to='food.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=100)),
                ('menu_item_image', models.ImageField(default='menu_item_default.jpg', upload_to='menu_item_images')),
                ('menu_item_price', models.IntegerField()),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='food.menucategory')),
            ],
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='food.restaurant'),
        ),
    ]
