# Generated by Django 4.2 on 2024-09-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_menucategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='food.restaurant'),
        ),
    ]
