# Generated by Django 4.2 on 2024-09-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_menucategory_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=100)),
                ('menu_item_image', models.ImageField(default='menu_item_default.jpg', upload_to='menu_item_images')),
                ('menu_item_price', models.IntegerField()),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='food.menucategory')),
            ],
        ),
    ]
