# Generated by Django 4.2 on 2024-09-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant_image', models.ImageField(default='restaurant_details-img.jpg', upload_to='restaurant_details_images')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_imgs', to='food.restaurant')),
            ],
        ),
    ]
